import {LegalShell} from '@/components/legal-shell';
export default function Privacy(){return <LegalShell title="Privacy Policy" kicker="YOUR DATA">
<p>This policy explains information handled by Tropeamine Packs and how it is used. A shorter summary is available on the <a href="/data">What Data We Collect</a> page.</p>
<h2>Information you provide or connect</h2><p>When you sign in with Google, authentication may provide an account identifier, email address, name and profile image. Tropeamine may also store profile information you choose to provide, including a display name, username, bio, pronouns, favorite series and profile visibility setting.</p>
<h2>Collection and game data</h2><p>We store information needed to operate your collection, including cards and editions owned, quantities and acquisition times, Ink and Shard balances, currency changes, favorites, showcase selections, badges, claimed rewards, binder preferences, theme/accent choices and onboarding state.</p>
<h2>How we use information</h2><p>We use this information to authenticate accounts, save and display collections, operate the virtual economy, remember preferences, provide site features, protect the service from abuse, troubleshoot problems and maintain the project.</p>
<h2>Service providers</h2><p>Tropeamine Packs uses third-party infrastructure to operate. Supabase provides authentication, database and storage services, and Vercel hosts and delivers the web application. Those providers may process technical information necessary to provide, secure and operate their services under their own terms and privacy practices.</p>
<h2>Browser and guest data</h2><p>The site may use browser storage to remember local collection or interface state. The unsigned free demo pack is intended as a local demonstration: its pulls are not added to a Tropeamine account or saved to an account binder.</p>
<h2>What Google sign-in does not mean</h2><p>Using Google to authenticate does not by itself give Tropeamine Packs access to Gmail, Google Drive, your Google Photos library, contacts, or other unrelated Google content.</p>
<h2>Sharing and sale</h2><p>We do not operate Tropeamine Packs as a business for selling users' personal information. Information may be processed by service providers as necessary to run the site, or disclosed when required by law or needed to protect the service and its users.</p>
<h2>Your choices</h2><p>You can choose not to create an account and use features made available to guests. Account/profile editing features allow certain profile information to be changed. A process for privacy, access and deletion requests will be published with public contact information before wider release.</p>
<h2>Retention and security</h2><p>Account and collection information may be retained while an account is active and as reasonably necessary to operate, secure and maintain the service. No internet service can guarantee absolute security.</p>
<h2>Children</h2><p>Tropeamine Packs is not designed as a service directed to children. If the project's audience or account requirements change, this policy will be updated accordingly.</p>
<h2>Changes</h2><p>We may update this policy as the site's features and data practices change. Material updates will be reflected by changing the effective date above.</p>
</LegalShell>}