import {LegalShell} from '@/components/legal-shell';
export default function Terms(){return <LegalShell title="Terms of Service" kicker="THE FINE PRINT">
<h2>1. About Tropeamine Packs</h2><p>Tropeamine Packs is an unofficial, fan-made digital collecting project. It is not affiliated with, endorsed by, sponsored by, or authorized by the authors, publishers, studios, licensors, or other rights holders associated with the books, characters, series, titles, trademarks, or other third-party intellectual property referenced on the site.</p>
<h2>2. Fan art and intellectual property</h2><p>Character cards and artwork on Tropeamine Packs are unofficial fan interpretations created for this project and are not official depictions or licensed artwork unless a specific item expressly says otherwise. Tropeamine Packs does not claim ownership of the underlying third-party characters, stories, series, titles, trademarks, or other intellectual property. Those rights remain with their respective owners. References to third-party works do not imply permission, sponsorship, endorsement, or affiliation.</p>
<p>If a rights holder has a concern about material appearing on the site, we intend to provide a contact channel for rights-related requests. Public contact information will be added as the project is prepared for wider release.</p>
<h2>3. Accounts</h2><p>Some features require an account. You are responsible for activity performed through your account and for providing accurate account information. Google sign-in is used for authentication; signing in does not give Tropeamine Packs access to your Gmail or Google Drive.</p>
<h2>4. Ink, Shards and digital cards</h2><p>Ink, Shards, cards, foil editions, treatments, achievements and similar items are virtual features of Tropeamine Packs. They have no cash value, are not cryptocurrency, are not redeemable for money, and do not represent ownership of the underlying intellectual property. Unless the site expressly introduces an authorized feature stating otherwise, these items are not transferable or tradable between users.</p>
<h2>5. Fair use of the service</h2><p>Do not attempt to exploit, automate, manipulate, interfere with, or gain unauthorized access to the site, its economy, accounts, databases, or other users' data. We may correct balances, collection records, or other state affected by bugs, abuse, or technical errors.</p>
<h2>6. Availability and changes</h2><p>Tropeamine Packs is an evolving fan project. Features, card pools, virtual balances, artwork and availability may change, be corrected, or be removed. We do not promise that any feature or digital item will remain available permanently.</p>
<h2>7. Disclaimer</h2><p>The service is provided on an as-available basis. To the extent permitted by law, no guarantee is made that it will always be uninterrupted, error-free, or free from loss of locally stored or account data.</p>
<h2>8. Changes to these terms</h2><p>These terms may be updated as Tropeamine Packs changes. The effective date at the top of this page will be updated when material changes are published.</p>
</LegalShell>}