export type Card = {id:string; name:string; number:string; rarity:'Common'|'Uncommon'|'Rare'|'Legendary'; variant:string; hue:string; shelf:string; genre:string; series:string; author:string; tags:string[]; bio:string; appearances?:string; relationships?:string; quote?:string; image?:string; back?:string; packs?:string[]; available:boolean; adult?:boolean};
const names = ['Noah','Sam','Cassandra','Rachel','Morgan'];
const hues = ['olive','wine','violet','blue','copper'];
const warlockCards:Card[] = Array.from({length:9},(_,i)=>({id:`war-${i+1}`,name:names[i%5],number:`WAR-${String(i%5+1).padStart(3,'0')}${i>4?'A':''}`,rarity:i===8?'Legendary':i>4?'Rare':i===2||i===4?'Uncommon':'Common',variant:i>4?'Foil edition':'Base edition',hue:hues[i%5],shelf:'His Shelf',genre:'HaremLit',series:'Warlock',author:'Daniel Kensington',tags:['Demo entry'],bio:'An open page, waiting for the creator. Character lore, appearances, and relationships can be added here.',packs:['haremlit-1'],available:true}));

const lightsOutDrafts:Card[] = [
{id:'lights-out-aly',name:'Alyssa “Aly” Cappellucci',number:'LO-001',rarity:'Rare',variant:'Base edition',hue:'wine',shelf:'Her Shelf',genre:'Dark Romance',series:'Lights Out',author:'Navessa Allen',tags:['Trauma nurse','Black cat','Mask kink','@aly.aly.oxen.free'],bio:'A trauma ER nurse with a tired, confident, defiant edge. Aly is serious about her work, drawn to danger on her own terms, and far harder to rattle than most people expect.',appearances:'Lights Out',relationships:'Josh Hammond · Fred',quote:'Trauma people are my people.',packs:['dark-romance-1'],available:false},
{id:'lights-out-josh',name:'Josh Hammond',number:'LO-002',rarity:'Legendary',variant:'Base edition',hue:'blue',shelf:'Her Shelf',genre:'Dark Romance',series:'Lights Out',author:'Navessa Allen',tags:['The Faceless Man','Cybersecurity specialist','Protective','@the.faceless.man'],bio:'Quiet, brilliant, and intensely protective, Josh balances the anonymous danger of the Faceless Man with a thoughtful, patient, surprisingly gentle side. His past shapes his need for control, care, and protection—especially when it comes to Aly.',appearances:'Lights Out',relationships:'Alyssa “Aly” Cappellucci',packs:['dark-romance-1'],available:false},
{id:'caught-up-nico',name:'Nico “Junior” Trocci',number:'CU-001',rarity:'Legendary',variant:'Base edition',hue:'copper',shelf:'Her Shelf',genre:'Dark Romance',series:'Caught Up',author:'Navessa Allen',tags:['NT95','Mafia enforcer','Biker mask','Protective'],bio:'Known online as NT95, Nico is a dangerous mafia enforcer with a deeply loyal streak. Behind the orange heart-and-X biker mask is the longtime supporter who has quietly followed Lo’s work for years.',appearances:'Caught Up',relationships:'Lauren “Lo” Marchetti',packs:['dark-romance-1'],available:false},
{id:'caught-up-lo',name:'Lauren “Lo” Marchetti',number:'CU-002',rarity:'Rare',variant:'Base edition',hue:'violet',shelf:'Her Shelf',genre:'Dark Romance',series:'Caught Up',author:'Navessa Allen',tags:['Velvet co-owner','Me4U creator','Sex-work advocate','Bookish at heart'],bio:'Confident, independent, and unapologetic, Lo built an adult identity entirely her own. She is a Velvet co-owner, creator on Me4U, outspoken advocate, lifelong reader, and fiercely nurturing presence to the people—and dog—she loves.',appearances:'Caught Up',relationships:'Nico “Junior” Trocci · Walter',packs:['dark-romance-1'],available:false},
{id:'game-on-tyler',name:'Tyler Neumann',number:'GO-001',rarity:'Legendary',variant:'Base edition',hue:'olive',shelf:'Her Shelf',genre:'Dark Romance',series:'Game On',author:'Navessa Allen',tags:['Theo Strickland','Underground bookie','Calculating','Revenge'],bio:'A 25-year-old underground bookie operating under the alias Theo Strickland. Competitive, provocative, calculating, and dangerous, Tyler mixes a playful sarcastic edge with a relentless drive for control and revenge.',appearances:'Game On',relationships:'Stella McCormick · Blake McCormick',packs:['dark-romance-1'],available:false},
{id:'game-on-stella',name:'Stella McCormick',number:'GO-002',rarity:'Rare',variant:'Base edition',hue:'wine',shelf:'Her Shelf',genre:'Dark Romance',series:'Game On',author:'Navessa Allen',tags:['Tattoo artist','Black cat','Alternative','Fiercely loyal'],bio:'A 35-year-old tattoo artist with an icy, sarcastic exterior and a fiercely loyal core. Stella comes from wealth but built her tattoo parlor herself, wears her alternative style proudly, and will put herself directly in the line of fire to protect the people she loves.',appearances:'Game On',relationships:'Tyler Neumann · Blake McCormick · Amos',packs:['dark-romance-1'],available:false}
];

export const initialCards:Card[] = [...warlockCards,...lightsOutDrafts];
export type RequestBook={id:string;title:string;author:string;genre:string;tags:string;reference?:string;status:string;approved:boolean;characters:{name:string;sfw:number;adult:number}[]};
export const initialRequests:RequestBook[]=[{id:'r1',title:'Fourth Wing',author:'Rebecca Yarros',genre:'Romantasy',tags:'Demo votes',status:'Requested',approved:true,characters:[{name:'Violet Sorrengail',sfw:132,adult:27},{name:'Xaden Riorson',sfw:121,adult:41},{name:'Rhiannon Matthias',sfw:46,adult:8}]},{id:'r2',title:'Warlock',author:'Daniel Kensington',genre:'HaremLit',tags:'Demo votes',status:'In Progress',approved:true,characters:[{name:'Morgan',sfw:64,adult:18},{name:'Rachel',sfw:52,adult:14},{name:'Cassandra',sfw:48,adult:17}]}];
export const normalize=(s:string)=>s.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
